import React, { useState } from 'react';
import { X, Plus, Save, Trash2, ImagePlus } from 'lucide-react';
import { useStore } from '../../context/StoreContext';
import { AVAILABLE_COLORS } from '../../data/initialData';
import { ProductImage } from '../ProductImage';

export const ProductFormModal = ({ productToEdit, onClose }) => {
  const { addProduct, updateProduct, categories, sizes, addCategory, addSize, deleteSize, deleteCategory, isStaff, generateSku } = useStore();

  const selectableCategories = categories.filter((c) => c !== 'ทั้งหมด');

  const [name, setName] = useState(productToEdit?.name || '');
  // SKU is generated by the system — kept fixed for the lifetime of this form
  const [sku] = useState(() => productToEdit?.sku || generateSku());
  const [category, setCategory] = useState(productToEdit?.category || selectableCategories[0] || '');
  const [price, setPrice] = useState(productToEdit?.price || 390);
  const [wholesalePrice, setWholesalePrice] = useState(productToEdit?.wholesalePrice ?? (isStaff ? 0 : 290));
  const [cost, setCost] = useState(productToEdit?.cost ?? (isStaff ? 0 : 180));
  const [svgType, setSvgType] = useState(productToEdit?.svgType || 'tshirt');
  const [imageUrl, setImageUrl] = useState(productToEdit?.imageUrl || '');
  const [imageError, setImageError] = useState('');
  const [description, setDescription] = useState(productToEdit?.description || '');

  const [selectedSizes, setSelectedSizes] = useState(productToEdit?.sizes || ['S', 'M', 'L', 'XL']);
  const [selectedColors, setSelectedColors] = useState(
    productToEdit?.colors || [
      { name: 'สีดำ', hex: '#1e293b' },
      { name: 'สีขาว', hex: '#ffffff' },
    ]
  );

  // Variant Matrix state: key = `${size}-${colorName}` -> qty
  const [stockMatrix, setStockMatrix] = useState(productToEdit?.stockMatrix || {});

  // Inline creation of new sizes / categories
  const [newSize, setNewSize] = useState('');
  const [newCategory, setNewCategory] = useState('');
  const [listError, setListError] = useState('');

  const handleToggleSize = (size) => {
    setSelectedSizes((prev) =>
      prev.includes(size) ? prev.filter((s) => s !== size) : [...prev, size]
    );
  };

  const handleAddSize = () => {
    const result = addSize(newSize);
    if (!result.success) {
      setListError(result.error);
      return;
    }
    setSelectedSizes((prev) => (prev.includes(result.value) ? prev : [...prev, result.value]));
    setNewSize('');
    setListError('');
  };

  const handleDeleteSize = (sz) => {
    const result = deleteSize(sz);
    if (!result.success) {
      setListError(result.error);
      return;
    }
    setSelectedSizes((prev) => prev.filter((s) => s !== sz));
    setListError('');
  };

  const handleAddCategory = () => {
    const result = addCategory(newCategory);
    if (!result.success) {
      setListError(result.error);
      return;
    }
    setCategory(result.value);
    setNewCategory('');
    setListError('');
  };

  const handleDeleteCategory = () => {
    const result = deleteCategory(category);
    if (!result.success) {
      setListError(result.error);
      return;
    }
    setCategory(selectableCategories.filter((c) => c !== category)[0] || '');
    setListError('');
  };

  const handleToggleColor = (colorObj) => {
    setSelectedColors((prev) =>
      prev.some((c) => c.name === colorObj.name)
        ? prev.filter((c) => c.name !== colorObj.name)
        : [...prev, colorObj]
    );
  };

  const handleMatrixChange = (size, colorName, val) => {
    const key = `${size}-${colorName}`;
    setStockMatrix((prev) => ({
      ...prev,
      [key]: Math.max(0, parseInt(val) || 0),
    }));
  };

  // Photos are stored inline in localStorage, so shrink them to a thumbnail-sized JPEG first
  const handleImageSelect = (e) => {
    const file = e.target.files?.[0];
    e.target.value = '';
    if (!file) return;
    if (!file.type.startsWith('image/')) {
      setImageError('ไฟล์นี้ไม่ใช่รูปภาพ');
      return;
    }

    const reader = new FileReader();
    reader.onload = (evt) => {
      const img = new Image();
      img.onload = () => {
        const MAX = 500;
        const scale = Math.min(1, MAX / Math.max(img.width, img.height));
        const canvas = document.createElement('canvas');
        canvas.width = Math.round(img.width * scale);
        canvas.height = Math.round(img.height * scale);
        canvas.getContext('2d').drawImage(img, 0, 0, canvas.width, canvas.height);
        setImageUrl(canvas.toDataURL('image/jpeg', 0.75));
        setImageError('');
      };
      img.onerror = () => setImageError('เปิดไฟล์รูปนี้ไม่ได้');
      img.src = evt.target.result;
    };
    reader.onerror = () => setImageError('อ่านไฟล์รูปไม่สำเร็จ');
    reader.readAsDataURL(file);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!name || selectedSizes.length === 0 || selectedColors.length === 0) return;

    // Ensure all size-color combinations exist in stockMatrix
    const finalMatrix = { ...stockMatrix };
    selectedSizes.forEach((sz) => {
      selectedColors.forEach((col) => {
        const key = `${sz}-${col.name}`;
        if (finalMatrix[key] === undefined) {
          finalMatrix[key] = 10; // Default stock
        }
      });
    });

    const payload = {
      sku,
      name,
      category,
      price: parseFloat(price),
      wholesalePrice: parseFloat(wholesalePrice),
      cost: parseFloat(cost),
      sizes: selectedSizes,
      colors: selectedColors,
      stockMatrix: finalMatrix,
      svgType,
      imageUrl,
      description,
      // Staff cannot see or enter cost prices — the flag clears once an owner saves the product
      needsCostReview: isStaff,
    };

    if (productToEdit) {
      updateProduct(productToEdit.id, payload);
    } else {
      addProduct(payload);
    }
    onClose();
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-card" style={{ maxWidth: '680px' }} onClick={(e) => e.stopPropagation()}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.25rem' }}>
          <h3 style={{ fontSize: '1.2rem', fontWeight: '700' }}>
            {productToEdit ? 'แก้ไขข้อมูลสินค้า' : 'เพิ่มสินค้าเสื้อผ้าใหม่'}
          </h3>
          <button onClick={onClose} style={{ background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer' }}>
            <X size={22} />
          </button>
        </div>

        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
          {/* General Fields Grid */}
          <div className="grid-responsive" style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '1rem' }}>
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '4px', fontWeight: '600' }}>
                ชื่อสินค้า
              </label>
              <input
                type="text"
                className="input-field"
                required
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="เช่น เสื้อยืด Cotton 100% Oversize"
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '4px', fontWeight: '600' }}>
                รหัส SKU สินค้า (ระบบสร้างให้อัตโนมัติ)
              </label>
              <div
                className="input-field"
                style={{ display: 'flex', alignItems: 'center', color: '#38bdf8', fontWeight: '700', background: '#0f172a', cursor: 'default' }}
              >
                {sku}
              </div>
            </div>
          </div>

          <div className="grid-responsive" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '4px', fontWeight: '600' }}>
                หมวดหมู่
              </label>
              <div style={{ display: 'flex', gap: '0.4rem' }}>
                <select
                  className="input-field"
                  style={{ flex: 1 }}
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                >
                  {selectableCategories.map((cat) => (
                    <option key={cat} value={cat}>
                      {cat}
                    </option>
                  ))}
                </select>
                <button
                  type="button"
                  className="btn-secondary"
                  style={{ padding: '0 0.6rem' }}
                  title="ลบหมวดหมู่ที่เลือก"
                  onClick={handleDeleteCategory}
                >
                  <Trash2 size={16} />
                </button>
              </div>
              <div style={{ display: 'flex', gap: '0.4rem', marginTop: '0.4rem' }}>
                <input
                  type="text"
                  className="input-field"
                  style={{ flex: 1 }}
                  placeholder="เพิ่มหมวดหมู่ใหม่..."
                  value={newCategory}
                  onChange={(e) => setNewCategory(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      handleAddCategory();
                    }
                  }}
                />
                <button
                  type="button"
                  className="btn-secondary"
                  style={{ padding: '0 0.6rem' }}
                  title="เพิ่มหมวดหมู่"
                  onClick={handleAddCategory}
                >
                  <Plus size={16} />
                </button>
              </div>
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '4px', fontWeight: '600' }}>
                รูปสินค้า (รูปถ่ายจริง)
              </label>
              <div style={{ display: 'flex', gap: '0.6rem', alignItems: 'center' }}>
                <div style={{ width: 64, height: 64, flexShrink: 0, background: '#0f172a', borderRadius: '10px', border: '1px solid var(--bg-card-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>
                  <ProductImage
                    imageUrl={imageUrl}
                    svgType={svgType}
                    color={selectedColors[0]?.hex || '#8b5cf6'}
                    className="w-10 h-10"
                    alt={name}
                  />
                </div>

                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem', flex: 1 }}>
                  <label className="btn-secondary" style={{ cursor: 'pointer', justifyContent: 'center', fontSize: '0.8rem', padding: '0.45rem' }}>
                    <ImagePlus size={16} /> {imageUrl ? 'เปลี่ยนรูป' : 'อัปโหลดรูปสินค้า'}
                    <input type="file" accept="image/*" onChange={handleImageSelect} style={{ display: 'none' }} />
                  </label>
                  {imageUrl && (
                    <button
                      type="button"
                      className="btn-secondary"
                      style={{ justifyContent: 'center', fontSize: '0.8rem', padding: '0.45rem', color: '#f87171', borderColor: '#f87171' }}
                      onClick={() => setImageUrl('')}
                    >
                      <Trash2 size={14} /> ลบรูป
                    </button>
                  )}
                </div>
              </div>
              {imageError && <div style={{ color: '#f87171', fontSize: '0.78rem', marginTop: '4px' }}>{imageError}</div>}
              {!imageUrl && (
                <div style={{ fontSize: '0.72rem', color: '#64748b', marginTop: '4px' }}>
                  ถ้ายังไม่มีรูป ระบบจะใช้ไอคอนเสื้อผ้าแทนไปก่อน
                </div>
              )}
            </div>
          </div>

          {/* Pricing Fields */}
          <div className="grid-responsive" style={{ display: 'grid', gridTemplateColumns: isStaff ? '1fr' : '1fr 1fr 1fr', gap: '1rem' }}>
            {!isStaff && (
              <>
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '4px', fontWeight: '600' }}>
                ราคาที่รับมา / ต้นทุน (บาท)
              </label>
              <input
                type="number"
                className="input-field"
                required
                value={cost}
                onChange={(e) => setCost(e.target.value)}
              />
            </div>
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '4px', fontWeight: '600' }}>
                ราคาส่ง (บาท)
              </label>
              <input
                type="number"
                className="input-field"
                required
                value={wholesalePrice}
                onChange={(e) => setWholesalePrice(e.target.value)}
              />
            </div>
              </>
            )}
            <div>
              <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '4px', fontWeight: '600' }}>
                ราคาปลีก (บาท)
              </label>
              <input
                type="number"
                className="input-field"
                required
                value={price}
                onChange={(e) => setPrice(e.target.value)}
              />
            </div>
          </div>

          {isStaff && (
            <div style={{ fontSize: '0.8rem', color: '#94a3b8', background: '#0f172a', padding: '0.6rem 0.8rem', borderRadius: '8px', marginTop: '-0.5rem' }}>
              ราคาทุนและราคาส่งให้เจ้าของร้านกรอกภายหลัง — สินค้าที่เพิ่มจากโหมดพนักงานจะถูกทำเครื่องหมายไว้ให้ตรวจสอบ
            </div>
          )}

          {/* Size Selectors */}
          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '6px', fontWeight: '600' }}>
              ไซส์ที่มีขาย (Sizes)
            </label>
            <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', alignItems: 'center' }}>
              {/* Include sizes the product already uses even if they were removed from the master list */}
              {[...sizes, ...selectedSizes.filter((s) => !sizes.includes(s))].map((sz) => (
                <span key={sz} style={{ display: 'inline-flex', alignItems: 'center', gap: '2px' }}>
                  <button
                    type="button"
                    className={`size-chip ${selectedSizes.includes(sz) ? 'selected' : ''}`}
                    onClick={() => handleToggleSize(sz)}
                  >
                    {sz}
                  </button>
                  <button
                    type="button"
                    onClick={() => handleDeleteSize(sz)}
                    title={`ลบไซส์ ${sz}`}
                    style={{ background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', padding: 0 }}
                  >
                    <X size={13} />
                  </button>
                </span>
              ))}

              <input
                type="text"
                className="input-field"
                style={{ width: '110px', padding: '0.4rem 0.6rem' }}
                placeholder="ไซส์ใหม่..."
                value={newSize}
                onChange={(e) => setNewSize(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    e.preventDefault();
                    handleAddSize();
                  }
                }}
              />
              <button type="button" className="btn-secondary" style={{ padding: '0.4rem 0.7rem' }} onClick={handleAddSize}>
                <Plus size={16} />
              </button>
            </div>
          </div>

          {listError && (
            <div style={{ color: '#f87171', fontSize: '0.8rem', marginTop: '-0.75rem' }}>{listError}</div>
          )}

          {/* Color Selectors */}
          <div>
            <label style={{ display: 'block', fontSize: '0.85rem', color: '#94a3b8', marginBottom: '6px', fontWeight: '600' }}>
              สีที่มีขาย (Colors)
            </label>
            <div style={{ display: 'flex', gap: '0.6rem', flexWrap: 'wrap' }}>
              {AVAILABLE_COLORS.map((col) => {
                const isSelected = selectedColors.some((c) => c.name === col.name);
                return (
                  <button
                    type="button"
                    key={col.name}
                    className={`color-swatch-btn ${isSelected ? 'selected' : ''}`}
                    style={{ backgroundColor: col.hex }}
                    onClick={() => handleToggleColor(col)}
                    title={col.name}
                  />
                );
              })}
            </div>
          </div>

          {/* Variant Stock Matrix Table */}
          <div style={{ background: '#0f172a', padding: '1rem', borderRadius: '12px' }}>
            <div style={{ fontSize: '0.85rem', color: '#38bdf8', fontWeight: '700', marginBottom: '0.75rem' }}>
              กำหนดจำนวนสต็อกตั้งต้นตามไซส์และสี (Stock Variant Matrix)
            </div>

            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid #334155', textTransform: 'uppercase', color: '#94a3b8' }}>
                    <th style={{ padding: '6px', textAlign: 'left' }}>ไซส์ / สี</th>
                    {selectedColors.map((col) => (
                      <th key={col.name} style={{ padding: '6px', textAlign: 'center' }}>
                        {col.name}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {selectedSizes.map((sz) => (
                    <tr key={sz} style={{ borderBottom: '1px solid #1e293b' }}>
                      <td style={{ padding: '6px', fontWeight: '700', color: '#fff' }}>{sz}</td>
                      {selectedColors.map((col) => {
                        const key = `${sz}-${col.name}`;
                        const currentVal = stockMatrix[key] !== undefined ? stockMatrix[key] : 10;
                        return (
                          <td key={col.name} style={{ padding: '4px', textAlign: 'center' }}>
                            <input
                              type="number"
                              className="input-field"
                              style={{ width: '64px', textAlign: 'center', padding: '4px' }}
                              value={currentVal}
                              onChange={(e) => handleMatrixChange(sz, col.name, e.target.value)}
                            />
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Action Buttons */}
          <div style={{ display: 'flex', gap: '0.75rem', marginTop: '0.5rem' }}>
            <button type="button" className="btn-secondary" style={{ flex: 1 }} onClick={onClose}>
              ยกเลิก
            </button>
            <button type="submit" className="btn-primary" style={{ flex: 2 }}>
              <Save size={18} /> {productToEdit ? 'บันทึกการปรับปรุง' : 'เพิ่มสินค้าเข้าสต็อก'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
